name: tien_am
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: 5.7.0
  go_router: 14.2.7
  flutter_riverpod: 2.5.1
  dio_cache_interceptor: 3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  reactive_forms: 17.0.1
  get_it: 8.0.0
  google_fonts: 6.2.1
  pretty_dio_logger: 1.4.0
  logger: 2.4.0
  icons_plus: ^5.0.0
  riverpod_infinite_scroll: ^1.0.11
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4


flutter:
  uses-material-design: true
