name: mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  reactive_forms: ^16.1.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  get_it: ^7.6.4
  intl: ^0.18.0
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.jpg

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
        - asset: assets/fonts/Outfit-Medium.ttf

    - family: Outfit-Light
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf

    - family: Outfit-Medium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
